Repository galaxyproject/galaxy-language-server, pull requests merged in 2021-01, with the labels that each got.

#81 Prepare release 0.3.0
  README.md
  client/CHANGELOG.md
  client/README.md
  client/package.json
  docs/CONTRIBUTING.md
  server/CHANGELOG.md
  server/README.md
  server/galaxyls/services/language.py
  server/requirements.txt
Labels: documentation

#83 Fix wrong insert position for auto-generated code snippets
  README.md
  server/galaxyls/services/tools/document.py
  server/galaxyls/services/tools/generators/command.py
  server/galaxyls/services/tools/generators/snippets.py
  server/galaxyls/services/tools/generators/tests.py
  server/galaxyls/services/xml/document.py
  server/galaxyls/services/xml/nodes.py
  server/galaxyls/tests/unit/test_tools.py
Labels: bug, language server

#86 Fix autoclose tags and autocompletion behaviour
  server/galaxyls/services/completion.py
  server/galaxyls/services/context.py
  server/galaxyls/services/language.py
  server/galaxyls/services/xml/nodes.py
  server/galaxyls/tests/unit/test_completion.py
Labels: bug, language server, paper-cut

#87 add xref snippet
  client/src/snippets.json
Labels: enhancement, vscode extension

#88 Update docs
  README.md
  client/CHANGELOG.md
  client/README.md
  server/CHANGELOG.md
  server/README.md
Labels: documentation

#94 Update gx-tool snippet to latests IUC best practices
  client/src/snippets.json
Labels: enhancement, vscode extension

#100 Improve document root detection method
  server/galaxyls/server.py
  server/galaxyls/services/validation.py
  server/galaxyls/services/xml/document.py
  server/galaxyls/tests/unit/test_validation.py
Labels: bug, language server, paper-cut

#101 Minor improvements in Snippets
  client/src/snippets.json
Labels: enhancement, vscode extension

#104 Auto-reorder <param> attributes with commands
  README.md
  client/README.md
  client/package.json
  client/src/commands.ts
  client/src/extension.ts
  client/src/tagClosing.ts
  client/src/utils.ts
  server/galaxyls/features.py
  server/galaxyls/server.py
  server/galaxyls/services/language.py
  server/galaxyls/services/tools/common.py
  server/galaxyls/services/tools/constants.py
  server/galaxyls/services/tools/iuc.py
  server/galaxyls/services/xml/document.py
  server/galaxyls/services/xml/nodes.py
  server/galaxyls/tests/integration/__init__.py
  server/galaxyls/tests/integration/tools/__init__.py
  server/galaxyls/tests/integration/tools/test_iuc.py
  server/galaxyls/tests/integration/xml/__init__.py
  server/galaxyls/tests/integration/xml/test_document.py
  server/galaxyls/tests/integration/xml/test_element_node.py
  server/galaxyls/types.py
Labels: feature, language server, vscode extension
